# Generated by Django 3.2.2 on 2021-06-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=50, null=True)),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('time_interval', models.CharField(blank=True, max_length=10, null=True)),
                ('groups', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
