# Generated by Django 3.2.2 on 2021-06-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
